services:
  api-suporte:
    image: fightconnect/api-suporte:homolog
    build:
      context: .
      args:
        PROFILE: homolog
        PORT: 7086
    container_name: api-suporte
    restart: unless-stopped
    ports:
      - "${API_PORT:-7086}:7086"
    env_file:
      - config/.env
    environment:
      SERVER_PORT: 7086
      SPRING_PROFILES_ACTIVE: homolog
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      KEYCLOAK_ISSUER_URI: ${KEYCLOAK_ISSUER_URI}
      KEYCLOAK_JWK_SET_URI: ${KEYCLOAK_JWK_SET_URI}
      SPRING_RABBITMQ_HOST: ${RABBITMQ_HOST}
      SPRING_RABBITMQ_PORT: ${RABBITMQ_PORT}
      API_AUTH_URL: ${API_AUTH_URL}
      API_FIGHT_URL: ${API_FIGHT_URL}
      API_FINANCEIRO_URL: ${API_FINANCEIRO_URL}
      API_LOGS_URL: ${API_LOGS_URL}
      APP_STORAGE_BASE_PATH: ${APP_STORAGE_BASE_PATH:-/var/www/fightconnect.com.br/homologacao.fightconnect/tickets}
      APP_STORAGE_PUBLIC_BASE_URL: ${APP_STORAGE_PUBLIC_BASE_URL:-/tickets}
      APP_STORAGE_PUBLIC_HOST: ${APP_STORAGE_PUBLIC_HOST:-https://homologacao.fightconnect.com.br}
    volumes:
      - /var/www/fightconnect.com.br/homologacao.fightconnect/tickets:/var/www/fightconnect.com.br/homologacao.fightconnect/tickets
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - fightconnect-network
      - fightconnect-homolog-net

networks:
  fightconnect-network:
    driver: bridge
  fightconnect-homolog-net:
    external: true
