server.port=7086

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=${JWT_SECRET}

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
spring.rabbitmq.virtual-host=${RABBITMQ_VHOST:fightconnect-homolog}
spring.rabbitmq.connection-timeout=5000
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.acknowledge-mode=auto

api.auth.base-url=${API_AUTH_URL:http://localhost:7081}

# 🔒 Segurança: Desativar mensagens detalhadas de erro
server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-exception=false
