server.port=9086

spring.datasource.url=jdbc:postgresql://69.62.100.14:5432/bd_helpdesk
spring.datasource.username=postgres
spring.datasource.password=TeamFrank@
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false


logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.orm.jdbc.bind=INFO


springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

app.storage.base-path=/var/www/fightconnect.com.br/app.fightconnect/tickets
app.storage.public-base-url=/tickets
app.storage.public-host=https://app.fightconnect.com.br

app.mail.support-to=suporte@fightconnect.com.br

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=20MB

# === PUSH EVENTS (tem que bater com o worker) ===
app.rabbit.exchange=events.fightconnect
app.rabbit.routing-notify=notify


api.auth.base-url=http://localhost:9081
api.auth.timeout-ms=5000


jwt.secret=7f03a2e0-f9ac-47ca-b72f-76e9d4b67e45
jwt.expiration=86400000


spring.rabbitmq.host=69.62.100.14
spring.rabbitmq.port=5672
spring.rabbitmq.username=fightconnect
spring.rabbitmq.password=Gilvan1993@#@
spring.rabbitmq.connection-timeout=5000
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.acknowledge-mode=auto

spring.rabbitmq.listener.simple.prefetch=20
spring.rabbitmq.listener.simple.concurrency=1
spring.rabbitmq.listener.simple.max-concurrency=3

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-exception=true
