server.port=8080

# ===== DATABASE (DEV - Docker local) =====
spring.datasource.url=jdbc:postgresql://localhost:5432/helpdesk
spring.datasource.username=postgres
spring.datasource.password=-@VibeTex@2025@-
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA / HIBERNATE =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# (opcional) logs melhores
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE


springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha


spring.mail.host=smtp.seuprovedor.com
spring.mail.port=587
spring.mail.username=SEU_EMAIL
spring.mail.password=SUA_SENHA
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from=suporte@vibetex.com.br
app.mail.support-to=suporte@vibetex.com.br


#app.storage.base-path=/var/www/cedae.homologacao.vibetex.com.br/images
#app.storage.public-base-url=/images

app.storage.base-path=C:\\workspace\\images
app.storage.public-base-url=/images


spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=20MB


controlapp.base-url=http://69.62.104.13:6000/controlapp
controlapp.timeout-ms=5000


security.jwt.secret=c2730c0ff66de9789ed495137e90e159dadf84fc211ce872de438832dadc223bad96742d0f6c6f294a3f09a9a0426674b3d7667905eac79f563717bee1aca70d
security.jwt.issuer=ControlApp
security.jwt.audience=VibeService
