server.port=7086

spring.datasource.url=${DB_URL:jdbc:postgresql://69.62.100.14:5432/bd_helpdesk_homolog}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS}

jwt.secret=${JWT_SECRET}

spring.rabbitmq.host=${RABBIT_HOST:69.62.100.14}
spring.rabbitmq.username=${RABBIT_USER:fightconnect}
spring.rabbitmq.password=${RABBIT_PASS}

api.auth.base-url=${API_AUTH_URL:http://localhost:7081}

# 🔒 Segurança: Desativar mensagens detalhadas de erro
server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-exception=false
