server.port=9086

spring.datasource.url=${DB_URL:jdbc:postgresql://69.62.100.14:5432/bd_helpdesk}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.orm.jdbc.bind=INFO

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

app.storage.base-path=${STORAGE_PATH:/var/www/fightconnect.com.br/app.fightconnect/tickets}
app.storage.public-base-url=/tickets
app.storage.public-host=${STORAGE_HOST:https://app.fightconnect.com.br}

app.mail.support-to=suporte@fightconnect.com.br

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=20MB

# === PUSH EVENTS ===
app.rabbit.exchange=events.fightconnect
app.rabbit.routing-notify=notify

api.auth.base-url=${API_AUTH_URL:http://localhost:9081}
api.auth.timeout-ms=5000

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

spring.rabbitmq.host=${RABBIT_HOST:69.62.100.14}
spring.rabbitmq.port=${RABBIT_PORT:5672}
spring.rabbitmq.username=${RABBIT_USER:fightconnect}
spring.rabbitmq.password=${RABBIT_PASS}

spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.acknowledge-mode=auto

# 🔒 Segurança: Desativar mensagens detalhadas de erro em produção
server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-exception=false
